### ISSUE TITLE
使用get_danmaku没办法获取全部弹幕

### ISSUE THREAD

**Issue by huzi6702** [Passkou/bilibili-api#120]
已更新 bilibili-api  4.0.1
对于弹幕多的视频(弹幕数远大于2000)，所获取的弹幕数一直都只有2000
是不是我不会用？？
（刚入门python不久）

`BVid="BV1Zh411C7M5"`
`my_video = video.get_video_info(bvid=BVid) `
`danmu=video.get_danmaku(bvid=BVid,aid=my_video["aid"],page_id=my_video["pages"][0]["cid"],verify=verify,date=None)`

**Comment by Passkou** [comment]
应该需要获取历史弹幕，先用 [get_history_danmaku_index()](https://github.com/Passkou/bilibili_api/blob/main/docs/%E6%A8%A1%E5%9D%97/video.md#get_history_danmaku_index) 查询存在历史弹幕的日期，然后 [get_danmaku()](https://github.com/Passkou/bilibili_api/blob/main/docs/%E6%A8%A1%E5%9D%97/video.md#get_danmaku) 传入 date 参数，全部加上应该就是全部弹幕了

**Comment by und3r5h4ft** [comment]
使用了以下代码：
`BVid = "BV1Jz4y1U7WU"` 
 `danmaku_history_list = video.get_history_danmaku_index(BVid, verify=verify)` 
`for date_str in danmaku_history_list:`
     ` danmaku_date = datetime.strptime(date_str, '%Y-%m-%d')`
     ` danmaku = video.get_danmaku(BVid, page_id=video_detail['pages'][0]['cid'], date=danmaku_date, verify=verify)`
获得了从2-6到今天的每一天的弹幕，但是每一天的弹幕都是一模一样的，请问是何原因？谢谢

**Comment by und3r5h4ft** [comment]
使用了以下代码：
BVid = "BV1Jz4y1U7WU"
danmaku_history_list = video.get_history_danmaku_index(BVid, verify=verify)
for date_str in danmaku_history_list:
danmaku_date = datetime.strptime(date_str, '%Y-%m-%d')
danmaku = video.get_danmaku(BVid, page_id=video_detail['pages'][0]['cid'], date=danmaku_date, verify=verify)
获得了从2-6到今天的每一天的弹幕，但是每一天的弹幕都是一模一样的，请问是何原因？谢谢

> 应该需要获取历史弹幕，先用 [get_history_danmaku_index()](https://github.com/Passkou/bilibili_api/blob/main/docs/%E6%A8%A1%E5%9D%97/video.md#get_history_danmaku_index) 查询存在历史弹幕的日期，然后 [get_danmaku()](https://github.com/Passkou/bilibili_api/blob/main/docs/%E6%A8%A1%E5%9D%97/video.md#get_danmaku) 传入 date 参数，全部加上应该就是全部弹幕了

**Comment by Lancelot229** [comment]
https://github.com/Passkou/bilibili_api/issues/120#issuecomment-783059414
同楼上一样的问题，还请大神帮忙解答，小弟拜谢

**Comment by jinliwei1997** [comment]
同楼上, 似乎date不起作用, 会访问到date日期之后的弹幕

**Comment by Passkou** [comment]
已查到原因是接口更改了，但是要到v5版本再解决了，目前还在写。
如果急需使用的话可以自行修改一下代码。
https://github.com/Passkou/bilibili-api/blob/main/bilibili_api/video.py#L699
在这个位置插入以下代码即可
```python
api = {
  "url": "https://api.bilibili.com/x/v2/dm/web/history/seg.so"
}
```

**Comment by jinliwei1997** [comment]
已修改，看上去work了。
还有一个问题，就是接口只有日期吗，例如视频 BV1mi4y1b76M 是2020-04-03发布的，通过video.get_danmaku(bvid="BV1mi4y1b76M",page_id=page_id,date=datetime.date(2020,4,3),verify=verify) 获得了2000条弹幕，显然发布当天不止2000条弹幕，那其余的弹幕是没办法重新获取了吗？
或者更加直接一点，有没有办法获取某个视频的所有历史弹幕呢？在网上找了很久也没找到可行的方案。

**Comment by Passkou** [comment]
> 
> 
> 已修改，看上去work了。
> 还有一个问题，就是接口只有日期吗，例如视频 BV1mi4y1b76M 是2020-04-03发布的，通过video.get_danmaku(bvid="BV1mi4y1b76M",page_id=page_id,date=datetime.date(2020,4,3),verify=verify) 获得了2000条弹幕，显然发布当天不止2000条弹幕，那其余的弹幕是没办法重新获取了吗？
> 或者更加直接一点，有没有办法获取某个视频的所有历史弹幕呢？在网上找了很久也没找到可行的方案。

估计是不行，目前还没找到解决方案，我记得之前在哪看到过说视频根据一些指标（比如播放量）会有不同的弹幕容量。弹幕数量超过这个容量就不清楚怎么获取了

**Comment by Passkou** [comment]
v5不知道要写到什么时候，v4.0.2已修复该问题

**Comment by nghuyong** [comment]
感谢大佬编写了这么方便的API，在具体操作中我还是有点疑问：

我的目标是获取一个视频的全部弹幕，我理解的逻辑是：
1. 获取视频信息：`video = video.get_video_info(bvid=BVid)`
2. 获取视频发布到当前所有包含弹幕的日期（**需要按月进行遍历**）：`danmaku_history_list = video.get_history_danmaku_index()`
3. 遍历步骤2中所有的日期，获取每个指定日期的弹幕：`danmaku = get_danmaku(date)`

我的问题是步骤三是否会有遗漏或者说有上限，比如一天的弹幕量如果是上百万，是不是都可以拉取到？

**Comment by Passkou** [comment]
> 
> 
> 感谢大佬编写了这么方便的API，在具体操作中我还是有点疑问：
> 
> 我的目标是获取一个视频的全部弹幕，我理解的逻辑是：
> 
>     1. 获取视频信息：`video = video.get_video_info(bvid=BVid)`
> 
>     2. 获取视频发布到当前所有包含弹幕的日期（**需要按月进行遍历**）：`danmaku_history_list = video.get_history_danmaku_index()`
> 
>     3. 遍历步骤2中所有的日期，获取每个指定日期的弹幕：`danmaku = get_danmaku(date)`
> 
> 
> 我的问题是：
> 步骤二是需要鉴权的，获取的cookie的到期时间是多久？
> 步骤三是否会有遗漏或者说有上限，比如一天的弹幕量如果是上百万，是不是都可以拉取到？

Cookie 有效期大概是从登录那会开始计算往后推三个月。但是如果你网页版登出后可能会立即失效。
如果视频弹幕非常多，无法获取全部弹幕，每个视频弹幕池容量是有限制的，这个无法解决。

**Comment by nghuyong** [comment]
@Passkou  我实际测试一下 `bilibili_api.video.get_danmaku(bvid,page_id,verify,date)` 一天最多只能获取500个？
