### ISSUE TITLE
在开启clash的情况下的一些问题

### ISSUE THREAD

**Issue by Midolii** [Passkou/bilibili-api#122]
在使用了clash并且clash中system proxy选项开启的情况下, 
代码中必须使用代理的形式才可以调用api, 

from bilibili_api import video
import bilibili_api

bilibili_api.request_settings["proxies"] = {} # 里头填写你的代理

v = video.get_video_info(bvid="BV1uv411q7Mv")

print(v)

如果不使用代理形式, 就会出问题, 提示

requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.bilibili.com', port=443): Max retries exceeded with url: /x/web-interface/view?bvid=BV1uv411q7Mv (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**Comment by Passkou** [comment]
那个涉及到requests的问题了，我这里无法解答。你只能设置代理
