### ISSUE TITLE
需求：readlist模块

### ISSUE THREAD

**Issue by shaolone** [Passkou/bilibili-api#128]
类型：需求

版本：4.0.1

能不能增加文集模块
实例网页：https://www.bilibili.com/read/readlist/rl000010
api：https://api.bilibili.com/x/article/list/web/articles?id=8&jsonp=jsonp

**Comment by Passkou** [comment]
统一到 v5 版本时增加

**Comment by Passkou** [comment]
V5 已实现：https://github.com/Passkou/bilibili-api/blob/v5/bilibili_api/article.py#L54
