### ISSUE TITLE
调用读取弹幕接口时字符解码问题

### ISSUE THREAD

**Issue by Maxwilson1101** [Passkou/bilibili-api#129]
在调用接口获取弹幕时，遇到错误''utf-8' codec can't decode byte 0xf0'。初步排查错误后发现无法解码弹幕中的表情。在get_danmaku_g方法下添加如下字段可以解决bug。
![python](https://user-images.githubusercontent.com/45385029/109762724-0a692400-7c2c-11eb-9937-1f780e611d7a.png)

**Comment by Maxwilson1101** [comment]
在datatype == 6情况下decode方法添加了encoding='ISO-8859-1'参数

**Comment by Passkou** [comment]
理工视频出现了这个错误，参数提供一下

**Comment by Passkou** [comment]
啊这，突然发现你现在这个位置并不是弹幕内容。。而是crc32_id

**Comment by Passkou** [comment]
4.0.3 版本已解决此问题
