### ISSUE TITLE
get_danmaku爬取超炮弹幕报错

### ISSUE THREAD

**Issue by BILLYLIAOWEI** [Passkou/bilibili-api#131]
类型： BUG

版本：4.0.2

#get_danmaku 爬取超炮，超炮S，超炮T各集最新弹幕时发现，报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 0: invalid continuation byte
#第一季 第24集爬取有问题
#第二季 第23集爬取有问题
#其它集未出现问题
`
ei = bangumi.get_episode_info(epid = 84340)
bvid = ei['epList'][0]['bvid']
info = video.get_video_info(bvid=bvid)
page_id = info["pages"][23]["cid"]
danmaku = video.get_danmaku(bvid = bvid, page_id = page_id)
`

**Comment by Passkou** [comment]
和 #129 重复
