### ISSUE TITLE
【公告】bilibili-api v5 版本招人一起开发

### ISSUE THREAD

**Issue by Passkou** [Passkou/bilibili-api#132]
工程量有点大，最近事多很少有时间维护。。所以现在想找几个人一起开发。

# 简单要求如下：

1. 明白 Python 异步机制，能简单运用。
2. 能模仿现有代码风格。
3. 有充足的时间，足够细心和耐心。**有责任心**

# 一起维护方法：

1. 在该 Issue 下认领你想维护的模块
2. Fork 本仓库一份。
3. 从 v5 分支新建一个分支出去，命名为 module-xxx（xxx 为你认领的模块名）
4. 写好后发 PR 即可，向 v5 分支发起，和平常 PR 流程一样

基本框架我已经搭好了，你可以参照一下开发。

# 一些说明：

v5 分支下有 bilibili_api_old 文件夹，这是旧 API，供参考使用，请在 bilibili_api 文件夹下添加新模块。

有不明白的地方，在 <https://gitter.im/Passkou/bilibili-api> 下实时聊天。

# 模块认领情况：

+ [x] video.py -- @Passkou 
+ [x] audio.py（未认领）
+ [x] app.py（未认领）
+ [x] article.py（未认领）
+ [x] bangumi.py（未认领）
+ [x] channel.py -- @Mizar6
+ [x] dynamic.py -- @Passkou
+ [x] live.py -- @miaopeng233
+ [x] user.py -- @Passkou 
+ [x] favorite_list -- @Passkou

另外，如果你想长期维护这个项目，可以通过这次机会来展现你的水平和诚意，到时候可以直接给你仓库权限一起维护_(:з」∠)_

**Comment by Mizar6** [comment]
最近一直在用楼主的这个包记录B站UP主的信息，我想试试能不能帮上忙。
我可以先认领channel.py试试嘛（这个看上去稍微简单一点 Orz），如果试试看了之后没问题，我也可以视情况看看能不能帮忙维护其他模块。

**Comment by miaopeng233** [comment]
可以加我一个么，把 live 模块交给我

**Comment by Passkou** [comment]
> 
> 
> 可以加我一个么，把 live 模块交给我

可以试试，不过live模块比较麻烦

**Comment by miaopeng233** [comment]
我尽量，最近正好学一下websocket,这个模块我也一直在用。

**Comment by miaopeng233** [comment]
> > 可以加我一个么，把 live 模块交给我
> 
> 可以试试，不过live模块比较麻烦

白天要上班，不过晚上，和周六日可以写一写，公司也不怎么加班。
