### ISSUE TITLE
还是关于video模块的get_download_url()方法

### ISSUE THREAD

**Issue by compiledSuccessfully** [Passkou/bilibili-api#135]
作者  提出issue的还是我
昨天找到一个bilibili解析接口网站:    [https://www.guoxingjun.com/video/bilibili](url)
发现可能这个网站用的解析方法就是用了你的代码解析的:
![image](https://user-images.githubusercontent.com/29682883/111019373-bdd6d300-83f9-11eb-8d96-6b2c89256bcd.png)

但是问题在于: 
我就是打不开用您的video模块解析出来的链接,无法下载,就显示403 forbidden.
但是用着解析网站解析出来的链接就能下载.这是为何.

**Comment by Passkou** [comment]
不要滥用 Issue，这个已经超出模块范畴，自己去了解翻爬虫

**Comment by compiledSuccessfully** [comment]
非常感谢，问题解决了。
抱歉提了3个issue，
非常感谢你的api库和你的帮助！！！
ありがとうございます！！
