### ISSUE TITLE
上传速度比网页版慢很多，而且感觉很多块上传了不止一次

### ISSUE THREAD

**Issue by valkjsaaa** [Passkou/bilibili-api#139]
上传大视频的时候非常的慢，网页上传10分钟的视频，用 API 可能要一个多小时，经常被服务器 reset 而且有的块传了不止一次，有什么可能的原因吗？不知道 v5 会不会 fix 这个问题？

比如以下是一次特别特别长的上传的 callback 记录。比如 chunk 1 就上传了两次。

https://gist.github.com/valkjsaaa/7b4b75c72f41c53697c7c84d305689aa

**Comment by Passkou** [comment]
v5分支已经写进去了，你可以clone下来看看速度，这个上传视频我用的比较少所以不太清楚

**Comment by valkjsaaa** [comment]
我发现问题了。当 video.pyL1236 的 remain 为 0 的时候，最后一个 thread 一个 thread 会把整个视频重新上传一遍。我交一个 pull request 吧。

**Comment by valkjsaaa** [comment]
不过 v5 的 code 应该是没有这个 bug 的
