### ISSUE TITLE
提问：AttributeError: 'dict' object has no attribute 'get_danmaku' 麻烦大佬帮我解答一下为什么这里会报这个错误

### ISSUE THREAD

**Issue by Humber526** [Passkou/bilibili-api#142]
from bilibili_api import video
import re
import pandas as pd

# BVid、fileName
BVid = "BV1oW41157Na"
file_name = '刺客伍六七第一集.csv'

# 获取弹幕
my_video = video.get_video_info(bvid=BVid)
my_danmu = my_video.get_danmaku()
代码如上，谢谢大佬。

**Comment by valkjsaaa** [comment]
你用错了，是这么用的

··· python
from bilibili_api import video
import re
import pandas as pd

#BVid、fileName

BVid = "BV1oW41157Na"
file_name = '刺客伍六七第一集.csv'

#获取弹幕

my_video = video.get_video_info(bvid=BVid)
cid = my_video["pages"][0]["cid"]
my_danmu = video. get_danmaku(cid)
···
