### ISSUE TITLE
爬取弹幕功能只能爬取部分弹幕

### ISSUE THREAD

**Issue by 171098620** [Passkou/bilibili-api#148]
类型：问题

版本：4.0.4

如果直接爬取全部弹幕的话，在弹幕数较多时（比如超过1000条），那么只能够获取一半左右。如果先获取历史弹幕日期再根据日期每日获取，那每天最多也仅能获取1000条。总之就是在视频弹幕量大的时候无法获取全部弹幕

**Comment by Passkou** [comment]
![图片](https://user-images.githubusercontent.com/45550579/116065674-d48b6d80-a6b9-11eb-90f5-4f59df8f5f00.png)

![图片](https://user-images.githubusercontent.com/45550579/116065576-bd4c8000-a6b9-11eb-8588-6c08c58bdc72.png)
描述与实际测试情况不符。

另外历史弹幕只能最多获取 1k 条，这是b站的限制
