### ISSUE TITLE
给视频点赞报错：账号异常，操作失败

### ISSUE THREAD

**Issue by freedomgod** [Passkou/bilibili-api#149]
使用video.set_like()给一个视频点赞时，报错，信息如下：
`bilibili_api.exceptions.BilibiliException: 错误代码：137004, 信息：账号异常，操作失败`
而其他操作如转发都是没有问题的。
使用的版本是4.0.4

**Comment by Passkou** [comment]
试试 v4.1.0

`pip install bilibili-api==4.1.0`

Verify 类请传入 buvid3 参数以解决点赞时账号异常的问题，与 SESSDATA 一样在 Cookies 里头就能找到。

**Comment by freedomgod** [comment]
ok了，传入buvid3可以解决这个问题。
