### ISSUE TITLE
提问：TypeError: 'int' object is not subscriptable，为何会报这个错？

### ISSUE THREAD

**Issue by Humber526** [Passkou/bilibili-api#151]
```python
from bilibili_api import video
# from bilibili_api import Danmaku
# import re
# import pandas as pd

# BVid
BVid = "BV1L64y1i7HY"#设置全局Bvid

# 获取弹幕
my_video = video.get_video_info(bvid = BVid)
cid = my_video["pages"][0]["cid"]
my_danmu = video.get_danmaku(cid)
```

**Comment by Humber526** [comment]
> from bilibili_api import video
> 
> # from bilibili_api import Danmaku
> # import re
> # import pandas as pd
> # BVid
> BVid = "BV1L64y1i7HY"#设置全局Bvid
> 
> # 获取弹幕
> my_video = video.get_video_info(bvid = BVid)
> cid = my_video["pages"][0]["cid"]
> my_danmu = video.get_danmaku(cid)

之前还能运行的，现在就报错了

**Comment by Passkou** [comment]
V4.0.4 正确用法：
```python
my_danmu = video.get_danmaku(bvid=BVid, page_id=cid)
```
不知道你是哪个版本的。你参数传错了。
