### ISSUE TITLE
Channel-get_top10接口url的参数写死了，导致传其他tid失效

### ISSUE THREAD

**Issue by DichPoon** [Passkou/bilibili-api#153]
如下：
"channel": {
    "ranking": {
      "get_top10": {
        "url": "https://api.bilibili.com/x/web-interface/ranking/region?rid=160&day=3&original=0",
        "method": "GET",
        "verify": false,
        "params": {
          "rid": "tid，分区id",
          "day": "3，7"
        },
        "comment": "获取分区前十排行榜"

**Comment by DichPoon** [comment]
还有channel.json也错了，最外面应该用{}，目前用了[]

**Comment by Passkou** [comment]
没有人比你更懂 JSON
