### ISSUE TITLE
请问如何获取弹幕？

### ISSUE THREAD

**Issue by niujingjing** [Passkou/bilibili-api#155]
你好，感谢这么便利的项目。但是我在使用的时候，想获取弹幕但一直报错「视频弹幕已关闭」。请问是我的使用姿势不对吗？
感谢回复 _(:з」∠)_

**Comment by lfywork** [comment]
是不是因为弹幕的数目很大，所以请求次数会很多，导致请求被拦截了？

**Comment by Passkou** [comment]
个人测试并没有问题，试试 V5 版本获取弹幕，刚刚发布的

**Comment by lfywork** [comment]
> 是不是因为弹幕的数目很大，所以请求次数会很多，导致请求被拦截了？

我自己是遇到这个问题了，请问V5版本只是增加了api，有没有在稳定性上面有提高？还有是V5可以通过pip获取，还是说只能源码导入库

**Comment by Passkou** [comment]
> 
> 
> > 是不是因为弹幕的数目很大，所以请求次数会很多，导致请求被拦截了？
> 
> 我自己是 在爬取视频底下的评论 遇到这个问题了，请问V5版本只是增加了api？，有没有在稳定性上面有提高？V5可以通过pip获取？还是说只能源码导入库

V5 修改了很多架构，可以用 pip 更新用，不过文档还没还没完成，反正我测试是正常的

**Comment by niujingjing** [comment]
升级 V5 之后获取弹幕，遇到报错如下：
```python
  File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 533, in get_danmakus
    view = await self.get_danmaku_view(page_index)
  File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 494, in get_danmaku_view
    json_data['dm_setting'] = read_settings(reader.bytes_string())
  File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 450, in read_settings
    data['font_size'] = reader_.float(True)
  File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/utils/BytesReader.py", line 57, in float
    data = struct.unpack("<f" if LE else ">f", self.__stream[self.__offset:self.__offset + 4])
struct.error: unpack requires a buffer of 4 bytes
```
 (:з」∠)抱歉，我是新手不太会写，有时间的话辛苦回复，感谢❤❤

**Comment by Passkou** [comment]
> 
> 
> 升级 V5 之后获取弹幕，遇到报错如下：
> 
> ```python
>   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 533, in get_danmakus
>     view = await self.get_danmaku_view(page_index)
>   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 494, in get_danmaku_view
>     json_data['dm_setting'] = read_settings(reader.bytes_string())
>   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 450, in read_settings
>     data['font_size'] = reader_.float(True)
>   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/utils/BytesReader.py", line 57, in float
>     data = struct.unpack("<f" if LE else ">f", self.__stream[self.__offset:self.__offset + 4])
> struct.error: unpack requires a buffer of 4 bytes
> ```
> 
> (:з」∠)抱歉，我是新手不太会写，有时间的话辛苦回复，感谢❤❤

BV号提供一下

**Comment by niujingjing** [comment]
> > 升级 V5 之后获取弹幕，遇到报错如下：
> > ```python
> >   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 533, in get_danmakus
> >     view = await self.get_danmaku_view(page_index)
> >   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 494, in get_danmaku_view
> >     json_data['dm_setting'] = read_settings(reader.bytes_string())
> >   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/video.py", line 450, in read_settings
> >     data['font_size'] = reader_.float(True)
> >   File "/Users/jingjing/Desktop/jingjing/projects/bilibili_bullet_spider/venv/lib/python3.9/site-packages/bilibili_api/utils/BytesReader.py", line 57, in float
> >     data = struct.unpack("<f" if LE else ">f", self.__stream[self.__offset:self.__offset + 4])
> > struct.error: unpack requires a buffer of 4 bytes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (:з」∠)抱歉，我是新手不太会写，有时间的话辛苦回复，感谢❤❤
> 
> BV号提供一下

BV1NK4y1X7hr

**Comment by Passkou** [comment]
一周没有回复，默认已解决

**Comment by niujingjing** [comment]
试了 PO 主的，没有问题哈。回看了下自己的代码，发现写入 date 参数后没有再遇到类似问题了，没发现是啥原因。先关掉了~感谢 PO 主 ❤
