### ISSUE TITLE
【漏洞】Credentials 说明页面 404

### ISSUE THREAD

**Issue by niujingjing** [Passkou/bilibili-api#157]
**Python 版本：** 3.x

**模块版本：** x.x.x

**运行环境：** Windows / Linux

**模块路径：** bilibili_api.xxxx

**报错信息：**

```
无
```

**报错代码：**

```python
无
```

---

https://github.com/Passkou/bilibili-api/blob/v4/docs/%E8%8E%B7%E5%8F%96%20Credential%20%E7%B1%BB%E6%89%80%E9%9C%80%E4%BF%A1%E6%81%AF

**Comment by niujingjing** [comment]
我发现从左侧点进页面是 OK 的，但是 README 里面的链接点不开~

**Comment by Passkou** [comment]
文档迁移到 https://github.com/Passkou/bilibili-api-docs 里面了，README 忘记改了
，另外官网也有：https://www.passkou.com/bilibili-api/#/get-credential
