### ISSUE TITLE
【提问】{关于历史弹幕的问题}

### ISSUE THREAD

**Issue by Chen-X666** [Passkou/bilibili-api#161]
**Python 版本：** 3.8

**模块版本：** 2.1.4

**运行环境：** Windows

---
danmakus = video.get_danmaku(bvid=bvid, date=startdate, verify=verify)
按照接口传入bvid, date，verify可是得到的历史弹幕是空的

**Comment by Passkou** [comment]
模块版本太低了，b站 API 早就改了，请先升级到最新版本
