### ISSUE TITLE
爬取弹幕测试的问题

### ISSUE THREAD

**Issue by Redamancy898** [Passkou/bilibili-api#163]
版本win10，vscode1.56.2（user setup）,python3.8

在使用video模块时，会出现如照片所示的问题。
![42~ AGW`FG3N}O`PWS{E5MU](https://user-images.githubusercontent.com/60684161/120886336-08927080-c620-11eb-945b-64afe5adddb5.png)
代码是您的测试代码 
![0`` U49OSZ}LCW %NCO{$2G](https://user-images.githubusercontent.com/60684161/120886359-1f38c780-c620-11eb-8cbe-4f753c6dbadc.png)

**Comment by Passkou** [comment]
请使用 Issue 模板提问
