### ISSUE TITLE
【漏洞】video模块的bug

### ISSUE THREAD

**Issue by Redamancy898** [Passkou/bilibili-api#164]
**Python 版本：** 3.8

**模块版本：** vscode1.56.2

**运行环境：** Windows

**模块路径：** bilibili_api.vedio

**报错信息：**

```
TypeError
   'type' object is not subscriptable

```

**报错代码：**

```python
# import asyncio
from bilibili_api import video

async def main():
    # 实例化 Video 类
    v = video.Video(bvid="BV1uv411q7Mv")
    # 获取信息
    info = await v.get_info()
    # 打印信息
    print(info)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

---

运行后出现报错信息的问题

**Comment by Passkou** [comment]
看你上一个 issue，你的文件路径包含中文名，改为英文试试

**Comment by Redamancy898** [comment]
> 看你上一个 issue，你的文件路径包含中文名，改为英文试试

改了，还是不行

**Comment by Passkou** [comment]
模块版本你填错了，我这边 5.0.1 测试正常

**Comment by Redamancy898** [comment]
> 模块版本你填错了，我这篇5.0.1测试正常

我是最新版本，然后我填的是运行软件的版本

**Comment by Chen-X666** [comment]
我也这样

**Comment by Chen-X666** [comment]
TypeError： 'type' object is not subscriptable

**Comment by Redamancy898** [comment]
> TypeError：'type' 对象不可下标

yep

**Comment by Passkou** [comment]
![图片](https://user-images.githubusercontent.com/45550579/120888871-39c56d80-c62d-11eb-93d0-17b9386d57a7.png)

明显是你们自己的问题，测试也是通过的，我这边也运行正常，找找你们配置是哪里有问题

**Comment by Passkou** [comment]
另外，提交报错代码时提供报错信息完整调用栈是最基本的

**Comment by Passkou** [comment]
已经找到问题了，这是 Python 3.9 以下特有的错误，更新到 5.0.2 就能解决了
