### ISSUE TITLE
【提问】上传视频成功，但是 B 站一直显示“审核中”

### ISSUE THREAD

**Issue by phigrey** [Passkou/bilibili-api#167]
**Python 版本：** 3.9

**模块版本：** 5.0.2

**运行环境：** MacOS

---

实现自动上传视频，代码如下
```
UPLOAD_CONFIG = {
  "copyright": 1, #"1 自制，2 转载。",
  "source": "", #"str, 视频来源。投稿类型为转载时注明来源，为原创时为空。",
  "desc": "", #"str, 视频简介。",
  "desc_format_id": 0,
  "dynamic": "", #"str, 动态信息。",
  "interactive": 0,
  "open_elec": 0, #"int, 是否展示充电信息。1 为是，0 为否。",
  "no_reprint": 1, #"int, 显示未经作者授权禁止转载，仅当为原创视频时有效。1 为启用，0 为关闭。",
  "subtitles": {
    "lan": "", #"字幕语言，不清楚作用请将该项设置为空",
    "open": 0
  },
  "tag": "测试", #"str, 视频标签。使用英文半角逗号分隔的标签组。示例：标签1,标签2,标签3",
  "tid": 208, #"int, 分区ID。可以使用 channel 模块进行查询。",
  "title": "测试一下", #"视频标题",
  "up_close_danmaku": False, #"bool, 是否关闭弹幕。",
  "up_close_reply": False, #"bool, 是否关闭评论。",
}

async def upload_videos(video_dir, cover_img):
  cover = open(cover_img, "rb")

  videos = []
  for filename in os.listdir(video_dir):
    if filename.endswith("mp4")
      video_file = os.path.join(video_dir, filename)
      videos.append(video.VideoUploaderPageObject(video_stream=open(video_file, "rb"), title=filename.split(".")[0]))

  config = UPLOAD_CONFIG

  credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

  uploader = video.VideoUploader(cover=cover, cover_type="jpg", pages=videos, config=config, credential=credential) 

  await uploader.start()

if __name__ == '__main__':
  folder = "folder_path"
  img = "cover.jpg"
  asyncio.get_event_loop().run_until_complete(upload_videos(folder, img))
```
尝试过手动上传，B 站状态可以由审核中到通过。但是自动上传的，就一直停留在审核中。
感谢你抽时间瞅瞅这个问题。

**Comment by phigrey** [comment]
我 debug 个下，解决了。以下关于机制的描述，希望能帮到有相同问题的人。
1、关于`preupload` 这个 b 站的API，其中需要的参数 `name` 是带有 `.mp4` 的。在 `video.py` 中 `__get_upload_info`
里的 `params.name`的值是 `page_object.title`，这部分的数值，在初始化 `VideoUploaderPageObject`, 即 `video.VideoUploaderPageObject(video_stream=open(video_file, "rb"), title=filename.split(".")[0])` 设置了，是没有 `.mp4` 的。为什么不带 `.mp4` 因为会报错。原因见第2点。
2、`__upload_video` 返回的 filename 是含有 `.mp4`， 而 `__submit` 里是用的 B 站 API `https://member.bilibili.com/x/vu/web/add` 里的参数 `videos[index].filename` 是不包含`.mp4` 后缀的。

我做了以上两部分的处理，结果是上传成功，审核通过。
刚开始使用 B 站 API，不熟悉，以上分析仅供参考，也就不提 PR 了。 @Passkou 如果有时间可以看看，给个结论。

**Comment by Passkou** [comment]
有点没看懂你说的。

VideoUploaderPageObject 里面的 title 本意是用做分 P 标题的，所以不应该带后缀。

如果你认为你这个可以解决，可以发个 PR。但是如果视频不是 mp4 会不会出问题？有空还请帮忙测试一下（最近准备期末考试事多），如果需要指定不同视频格式，可以考虑在 VideoUploaderPageObject 增加一个 format 属性，格式是视频格式，如：mp4, mkv 等。

**Comment by phigrey** [comment]
OK
