### ISSUE TITLE
【提问】显示账号未登录

### ISSUE THREAD

**Issue by 1479412322** [Passkou/bilibili-api#168]
**Python 版本：** 3.8.5

**模块版本：** 5.0.3

**运行环境：** Windows
---

```
  File "G:\bilibili\bilibili_robot\src\robot\robot.py", line 57, in updateVideoLike
    if await video.has_liked():
  File "G:\bilibili\bilibili_robot\src\bilibili_api\video.py", line 275, in has_liked
    return await request("GET", url, params=params, credential=self.credential) == 1
  File "G:\bilibili\bilibili_robot\src\bilibili_api\utils\network.py", line 153, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-101，信息：账号未登录。
```
credential验证过了，就算什么都不干直接调用也不行
```python
async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)
    video = video_m.Video(aid=170001, credential=credential)
    await video.like()
```

**Comment by phigrey** [comment]
MacOS + python 3.9 + 5.0.2 没有问题。
升个级呢，现在 `5.0.3` 了。还有是不是 Credential 的参数有误呢？

**Comment by phigrey** [comment]
B 站 logout 之后，我测试了下，能重现你的问题。因为原来的Credential 的值就无效了，需要[使用最新的 Credential 的值](https://www.passkou.com/bilibili-api/#/get-credential)。

**Comment by Passkou** [comment]
测试是通过的，应该是你的凭据无效了

https://github.com/Passkou/bilibili-api/runs/2752760479?check_suite_focus=true#step:5:94

**Comment by 1479412322** [comment]
![Code_FX8nJB5nQE](https://user-images.githubusercontent.com/49143646/120918622-e106db00-c6e7-11eb-893b-53c3e63475f2.png)

![chrome_jGy20Ji34c](https://user-images.githubusercontent.com/49143646/120918652-05fb4e00-c6e8-11eb-87bd-2a95635f531a.png)

**Comment by 1479412322** [comment]
@Passkou 账号在本地是登陆的，我特意重登了一次，还是一样

**Comment by 1479412322** [comment]
换大号也是一样

**Comment by Chen-X666** [comment]
我也还特意换了pyton3.9hhhh也提示101未登录，但是我感觉我填的应该是对的

**Comment by Chen-X666** [comment]
奇葩！！我找到问题了，我是sessdata错了，你按照"使用最新的 Credential 的值"那个链接去获取sessdata，不要直接在网络那里拿

**Comment by 1479412322** [comment]
> 
> 
> 奇葩！！我找到问题了，我是sessdata错了，你按照"使用最新的 Credential 的值"那个链接去获取sessdata，不要直接在网络那里拿

谢谢（刚才拿v4试了下，居然也不行了

**Comment by Passkou** [comment]
这个问题你们自己想办法解决吧，我和另外一个人都正常，测试用例也正常，不知道你们是怎么回事

**Comment by 1479412322** [comment]
> 
> 
> 这个问题你们自己想办法解决吧，我和另外一个人都正常，测试用例也正常，不知道你们是怎么回事

我本地测试也过了

**Comment by 1479412322** [comment]
`await dynamic_m.send_dynamic('qwq', credential=credential)`
接口返回错误代码-6

**Comment by 1479412322** [comment]
其中一个原因：复制过来的时候没删逗号，变成tuple了
