### ISSUE TITLE
【需求】[参数错误]修复

### ISSUE THREAD

**Issue by 1479412322** [Passkou/bilibili-api#171]
```
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.vc.bilibili.com:443 ssl:default [参数错误。]
```
解决方法：https://blog.csdn.net/qq_43210211/article/details/108379917
在`import asyncio`后面加上
`asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`

我觉得可以加到文档里

**Comment by Passkou** [comment]
如果在 Linux 或者其他系统这个方法就不能用了吧，因此并没有彻底解决问题。还需要继续研究一下

**Comment by Passkou** [comment]
v6.0.0 已解决
