### ISSUE TITLE
请问历史开发文档还在吗？谢谢

### ISSUE THREAD

**Issue by zhendong1993** [Passkou/bilibili-api#172]
您好，

我正在收集b站的数据来写论文。前几周看到过您的b站爬虫开发者文档，里面很详细的记载了如何调用api，现在找不到了。请问能够重新上传呢？ 十分感谢！如果您现在不打算上传的话，能够发送给我呢？（z.zuo.1@student.rug.nl 这个是我的邮箱，可以付费）

**Comment by Passkou** [comment]
因为最近很忙所以目前v5版本文档还没写，如果你想看之前的版本的文档，可以看看 v4 分支

https://github.com/Passkou/bilibili-api/tree/v4

**Comment by Passkou** [comment]
另外，下次提问请使用标准的 issue 模板
