### ISSUE TITLE
【需求】需要关于交互视频的操作

### ISSUE THREAD

**Issue by phigrey** [Passkou/bilibili-api#175]
妈妈从小教育我，自己的事情自己做，所以关于交互视频的需求，希望能在这个 repo 里完成

* 上传交互视频分 P (目前应该可以的，做个了 PR ，已经测试过了)
* 查看交互视频分 P 信息（这个和普通视频的接口不一样，需要增加）
* 故事树的提交（目前没有，需要增加）

**Comment by Passkou** [comment]
交互视频应该比较麻烦，而且需求不大，一般用这个模块都是做爬虫的，所以不打算写入。

**Comment by phigrey** [comment]
OK
