### ISSUE TITLE
【提问】给视频发送弹幕失败且出现RuntimeWarning

### ISSUE THREAD

**Issue by The-BlueFish** [Passkou/bilibili-api#177]
**Python 版本：** 3.8

**模块版本：** 5.1.1

**运行环境：** Windows10 64位

---
可能是我用得不太对，求求大神指正帮忙，教教我
我在这里贴一下相关代码和报错
from bilibili_api import video, Credential
from bilibili_api.utils import Danmaku
....
Danmaku.Danmaku()
Text = Danmaku.Danmaku(text=String, dm_time=23.3, pool=0)
V = video.Video(bvid=bvid)
verify = Credential(user['SESS'], user['bili_jct'], user['buvid3'])
V.credential = verify
V.send_danmaku(page_index=0, danmaku=Text)

报错
RuntimeWarning: coroutine 'Video.send_danmaku' was never awaited
  print(V.send_danmaku(page_index=0, danmaku=Text))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by Passkou** [comment]
https://www.passkou.com/bilibili-api/#/sync-executor

**Comment by The-BlueFish** [comment]
> https://www.passkou.com/bilibili-api/#/sync-executor
