### ISSUE TITLE
【提问】需要credential的操作 报 -400错

### ISSUE THREAD

**Issue by Cedric-Chen** [Passkou/bilibili-api#178]
**Python 版本：** 3.9.5 64 bit

**模块版本：** 5.1.1

**运行环境：** mac os big sur 11.4

---

需要credential的操作（如点赞/上传视频 时），会报错。
如readme中的点赞操作。

报错内容
ResponseCodeException: 接口返回错误代码：-400，信息：请求错误。

可能原因
+ credential 有错：检查无误。
+ ...

**Comment by Passkou** [comment]
今天的例行测试都是通过的：https://github.com/Passkou/bilibili-api/runs/2863373451

你看看是不是你获取方法有问题，参考：https://www.passkou.com/bilibili-api/#/get-credential

**Comment by Cedric-Chen** [comment]
非常不好意思-.-

```Python
credential = {"sessdata": "---"}
credential = Credential(**credential) # 正确
credential = Credential(*credential) # 错误
```
