### ISSUE TITLE
【提问】{爬取历史弹幕数量有限}

### ISSUE THREAD

**Issue by zhuangshuqi** [Passkou/bilibili-api#181]
**Python 版本：** 3.7.4

**模块版本：** 5.1.1

**运行环境：** Windows 

---
在爬取历史弹幕时，当  时间参数为 2021-06-21 时，爬取的弹幕数据时间包含  6-21，6-20，6-19，且总爬取量为1000。
请问如何能爬取每天弹幕数据，使得每天的弹幕数量都能达到1000？

**Comment by Passkou** [comment]
b站限制，无法解决

**Comment by zhuangshuqi** [comment]
好哒，谢谢大佬。
