### ISSUE TITLE
【漏洞】user get_dynamics 'extend_json' loads bug

### ISSUE THREAD

**Issue by biluoyuebai** [Passkou/bilibili-api#183]
**Python 版本：** 3.8

**模块版本：** x.x.x

**运行环境：** Windows & Linux

**模块路径：** bilibili_api.user

**报错信息：**

```
这里填写报错信息
```

**报错代码：**

```python
# 这里填写报错代码
```

---

https://github.com/Passkou/bilibili-api/blob/v5/bilibili_api/user.py#L290

我认为这行应当在 for 循环里边，否则只处理链表里最后一个动态的 extend_json 了。

**Comment by Passkou** [comment]
已修复，https://github.com/Passkou/bilibili-api/releases/tag/5.1.2
