### ISSUE TITLE
【提问】`video.py` 中 `get_chargers` 的语义

### ISSUE THREAD

**Issue by phigrey** [Passkou/bilibili-api#184]
**Python 版本：** 3.9

**模块版本：** 5.1.1

**运行环境：** MacOS

---

我的理解`get_chargers` 指的是获取充电的人。从B站应用上看这个充电是针对 up 主吧，也可以专门给某个视频充电吗？对B站应用不熟，望指导下。

**Comment by Passkou** [comment]
是获取给特定视频充电的用户吧

**Comment by phigrey** [comment]
* B 站页面上没看到给视频充电的入口，有给 up 充电的。
* `https://api.bilibili.com/x/ugcpay-rank/elec/month/up?up_mid=xxxx` 这也是个 API 查看充电人的，与视频无关。
* 现有的接口 work，只是语义和目前的用户行为对不上。`interactive_video` 那边我先不支持这个接口了。
* 如果你有什么新发现，告诉我下。

**Comment by Passkou** [comment]
从视频页面给up充电，显示在视频最后的充电感谢榜

**Comment by phigrey** [comment]
奥，OK
