### ISSUE TITLE
【提问】subscribe tag 和 unsubscribe tag 这两个接口和 video 的关系问题

### ISSUE THREAD

**Issue by phigrey** [Passkou/bilibili-api#185]
**Python 版本：** 3.9

**模块版本：** 5.1.1

**运行环境：** MacOS

---
我的理解如下：
* `add_tag` 和 `del_tag` 作为视频类的方法的缘由显而易见。
* `subscribe_tag` 和 `unsubscribe_tag` 只和 `tag` 有关，和 video 没有直接的关系，这两个方法是不是放在其他地方比较合适？

**Comment by Passkou** [comment]
现有接口没bug不要改了

**Comment by phigrey** [comment]
OK
