### ISSUE TITLE
【漏洞】网页显示”x小时前“导致日期不能被正确格式化

### ISSUE THREAD

**Issue by WhitePaper233** [Passkou/bilibili-api#192]
**Python 版本：** 3.9.6

**模块版本：** 6.0.1

**运行环境：** Windows

**模块路径：** bilibili_api.article

**报错信息：**

![RTU9IRBR_~J TKE{CF9@BE](https://user-images.githubusercontent.com/30739658/124626341-29651480-deb1-11eb-8cc0-672c3e47470a.png)

**报错代码：**

```python
meta['ctime'] = datetime.strptime(ctime_el.contents[0].strip(), "%Y-%m-%d").strftime("%Y-%m-%d")
```

---

很明显这是由于文章刚上传，网页显示“x小时前”导致日期不能正确被格式化的问题，但我没有完全读过api的代码，尚不明确其他模块是否存在类似的潜在问题，也没有想到一个高效率的解析实现方法(只能想到通过if判断不同情况)，希望作者大大能够进行修复

**Comment by Passkou** [comment]
他这个改版之后就显示个粗略的时间了，还没找到获取准确时间的 API 了，他这个文章页是服务端渲染，还得继续找找

**Comment by AngelicaRoot** [comment]
> 他这个改版之后就显示个粗略的时间了，还没找到获取准确时间的 API 了，他这个文章页是服务端渲染，还得继续找找

那这个问题在其他模块中是否可能复现？

**Comment by Passkou** [comment]
不会，因为这个获取信息是解析网页内容的，其他模块都是调用 JSON 接口的。另外我已经找到相应接口了，预计今天可以解决

**Comment by Passkou** [comment]
6.1.0 已解决
