### ISSUE TITLE
【提问】LiveDanmaku类 似乎失去了自动重连ws的功能

### ISSUE THREAD

**Issue by K-bai** [Passkou/bilibili-api#194]
**Python 版本：** 3.9

**模块版本：** 6.1.0

**运行环境：** Windows / Linux

---

4.x版本在网络波动的时候可以自动重连websocket，5.x换成aiohttp之后似乎失去了这个功能。请问是故意这样设计的吗？如果是的话能否给出自动重连的解决方案呢？

可以使用另一个协程，内部是一个循环，一直`await LiveDanmaku.connect()`来做到重连，但如果尝试重连时网络没有恢复，它就会一直阻塞在获取真实房间号，即使之后网络恢复了也无法连接弹幕直播间。且网络丢失后状态码竟然还是2，看了源码之后我的小脑袋瓜更加无法理解为什么了（

**Comment by Passkou** [comment]
试试：v6.1.1

**Comment by K-bai** [comment]
完全可以了！感谢新功能！
