### ISSUE TITLE
【提问】{article.Article(cvid)的问题}

### ISSUE THREAD

**Issue by LeewayTang** [Passkou/bilibili-api#197]
**Python 版本：** 3.8

**模块版本：** 6.1.1

**运行环境：** OSX

---

`article.Article(cvid)`返回的专栏文章一直是[动态令牌离线生成机制探究（2FA & TOTP）](https://www.bilibili.com/read/cv11717206/)，和cvid无关。

**Comment by Passkou** [comment]
手残测试的时候忘记改了，6.1.2 已修复

**Comment by LeewayTang** [comment]
好的(￣∀￣)-------- 原始邮件 --------发件人： Passkou ***@***.***>日期： 2021年7月13日周二 11:30收件人： Passkou/bilibili-api ***@***.***>抄送： LeewayTang ***@***.***>, Author ***@***.***>主    题： Re: [Passkou/bilibili-api] 【提问】{article.Article(cvid)的问题} (#197)

手残测试的时候忘记改了，6.1.2 已修复
