### ISSUE TITLE
【提问】{封面怎么上传？}

### ISSUE THREAD

**Issue by f-sky** [Passkou/bilibili-api#198]
**Python 版本：** 3.7

**模块版本：4.0.4

**运行环境：** Mac

---

封面上传的时候报错：bilibili_api.exceptions.BilibiliException: 错误代码：21008, 信息：封面必须由页面进行上传，不支持外部链接
封面是本地图片的路径。

**Comment by Passkou** [comment]
请升级到最新版本再提问
